"""schema inicial: usuarios, veiculos, leituras, alertas, diagnosticos, diagnostico_itens, password_resets, revoked_tokens

Revision ID: 6ccc395b5226
Revises: 
Create Date: 2026-09-03 19:34:40.439546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccc395b5226'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('RevokedTokenID', sa.Integer(), nullable=False),
    sa.Column('Jti', sa.String(length=36), nullable=False),
    sa.Column('ExpiraEm', sa.DateTime(), nullable=False),
    sa.Column('RevogadoEm', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('RevokedTokenID')
    )
    op.create_index(op.f('ix_revoked_tokens_Jti'), 'revoked_tokens', ['Jti'], unique=True)
    op.create_table('usuarios',
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('NomeUsuario', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=150), nullable=False),
    sa.Column('SenhaHash', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.Enum('motorista', 'admin', name='usuario_role'), nullable=False),
    sa.Column('CriadoEm', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('UsuarioID')
    )
    op.create_index(op.f('ix_usuarios_Email'), 'usuarios', ['Email'], unique=True)
    op.create_table('password_resets',
    sa.Column('PasswordResetID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('CodigoOtp', sa.String(length=6), nullable=False),
    sa.Column('ResetToken', sa.String(length=255), nullable=True),
    sa.Column('ExpiraEm', sa.DateTime(), nullable=False),
    sa.Column('Usado', sa.Boolean(), nullable=False),
    sa.Column('CriadoEm', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['UsuarioID'], ['usuarios.UsuarioID'], ),
    sa.PrimaryKeyConstraint('PasswordResetID'),
    sa.UniqueConstraint('ResetToken')
    )
    op.create_index(op.f('ix_password_resets_UsuarioID'), 'password_resets', ['UsuarioID'], unique=False)
    op.create_table('veiculos',
    sa.Column('VeiculoID', sa.Integer(), nullable=False),
    sa.Column('UsuarioID', sa.Integer(), nullable=False),
    sa.Column('Marca', sa.String(length=60), nullable=True),
    sa.Column('Modelo', sa.String(length=60), nullable=True),
    sa.Column('Ano', sa.Integer(), nullable=True),
    sa.Column('Placa', sa.String(length=20), nullable=True),
    sa.Column('Combustivel', sa.String(length=20), nullable=True),
    sa.Column('Conectado', sa.Boolean(), nullable=False),
    sa.Column('UltimaConexao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UsuarioID'], ['usuarios.UsuarioID'], ),
    sa.PrimaryKeyConstraint('VeiculoID')
    )
    op.create_index(op.f('ix_veiculos_UsuarioID'), 'veiculos', ['UsuarioID'], unique=False)
    op.create_table('alertas',
    sa.Column('AlertaID', sa.Integer(), nullable=False),
    sa.Column('VeiculoID', sa.Integer(), nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.Column('Origem', sa.String(length=30), nullable=False),
    sa.Column('Titulo', sa.String(length=120), nullable=False),
    sa.Column('Descricao', sa.Text(), nullable=True),
    sa.Column('Nivel', sa.String(length=20), nullable=False),
    sa.Column('Status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['VeiculoID'], ['veiculos.VeiculoID'], ),
    sa.PrimaryKeyConstraint('AlertaID')
    )
    op.create_index(op.f('ix_alertas_DataHora'), 'alertas', ['DataHora'], unique=False)
    op.create_index(op.f('ix_alertas_VeiculoID'), 'alertas', ['VeiculoID'], unique=False)
    op.create_table('diagnosticos',
    sa.Column('DiagnosticoID', sa.Integer(), nullable=False),
    sa.Column('VeiculoID', sa.Integer(), nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['VeiculoID'], ['veiculos.VeiculoID'], ),
    sa.PrimaryKeyConstraint('DiagnosticoID')
    )
    op.create_index(op.f('ix_diagnosticos_DataHora'), 'diagnosticos', ['DataHora'], unique=False)
    op.create_index(op.f('ix_diagnosticos_VeiculoID'), 'diagnosticos', ['VeiculoID'], unique=False)
    op.create_table('leituras',
    sa.Column('LeituraID', sa.Integer(), nullable=False),
    sa.Column('VeiculoID', sa.Integer(), nullable=False),
    sa.Column('DataHora', sa.DateTime(), nullable=False),
    sa.Column('VelocidadeKmh', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('Rpm', sa.Integer(), nullable=True),
    sa.Column('TempMotorC', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('TempOleoC', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('TempArrefecimentoC', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('TempArC', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('TensaoBateriaV', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['VeiculoID'], ['veiculos.VeiculoID'], ),
    sa.PrimaryKeyConstraint('LeituraID')
    )
    op.create_index(op.f('ix_leituras_DataHora'), 'leituras', ['DataHora'], unique=False)
    op.create_index(op.f('ix_leituras_VeiculoID'), 'leituras', ['VeiculoID'], unique=False)
    op.create_table('diagnostico_itens',
    sa.Column('DiagnosticoItemID', sa.Integer(), nullable=False),
    sa.Column('DiagnosticoID', sa.Integer(), nullable=False),
    sa.Column('Indicador', sa.String(length=60), nullable=False),
    sa.Column('Valor', sa.String(length=120), nullable=False),
    sa.Column('Observacao', sa.String(length=255), nullable=True),
    sa.Column('Referencia', sa.String(length=60), nullable=True),
    sa.Column('Alerta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['DiagnosticoID'], ['diagnosticos.DiagnosticoID'], ),
    sa.PrimaryKeyConstraint('DiagnosticoItemID')
    )
    op.create_index(op.f('ix_diagnostico_itens_DiagnosticoID'), 'diagnostico_itens', ['DiagnosticoID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostico_itens_DiagnosticoID'), table_name='diagnostico_itens')
    op.drop_table('diagnostico_itens')
    op.drop_index(op.f('ix_leituras_VeiculoID'), table_name='leituras')
    op.drop_index(op.f('ix_leituras_DataHora'), table_name='leituras')
    op.drop_table('leituras')
    op.drop_index(op.f('ix_diagnosticos_VeiculoID'), table_name='diagnosticos')
    op.drop_index(op.f('ix_diagnosticos_DataHora'), table_name='diagnosticos')
    op.drop_table('diagnosticos')
    op.drop_index(op.f('ix_alertas_VeiculoID'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_DataHora'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_veiculos_UsuarioID'), table_name='veiculos')
    op.drop_table('veiculos')
    op.drop_index(op.f('ix_password_resets_UsuarioID'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_usuarios_Email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_revoked_tokens_Jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
